apiVersion: batch/v1
kind: CronJob
metadata:
  name: nfs-file-mover-cron
spec:
  schedule: "0 18 * * *"  # каждый день в 18:00 UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: file-mover
              image: proget.isod.ic/docker.io/file-mover:latest
              # Default Always
              # imagePullPolicy: IfNotPresent
              # command: ["/bin/sh", "-c"]
              # args: ["sleep 100000"]
              env:
                - name: SOURCE_DIR
                  value: "/development/Light_Data/test-in"
                - name: TARGET_DIR
                  value: "/development/Light_Data/test-out"
                - name: STABLE_SECONDS
                  value: "3"
                - name: POLL_INTERVAL
                  value: "1"
              volumeMounts:
                - name: development
                  mountPath: /development/Light_Data
          restartPolicy: OnFailure
          volumes:
            - name: development
              nfs:
                server: development.isod.ic
                path: /Light_Data
                readOnly: false
